#!/usr/bin/env python3
"""Print documented Pydantic defaults without reading the process environment.

PYTHONPATH=services/analysis/src python scripts/export-runtime-settings.py
"""
from echora_analysis.settings import Settings


def template() -> str:
    lines = [
        '# Generated by scripts/export-runtime-settings.py. Do not edit defaults here.',
        '# Copy selected lines into .env and remove the leading comment marker.',
        '# All entries are commented so this catalog does not replace Compose defaults.',
        '# Secret values are blank. See docs/runtime-settings.md for deployment details.',
        '',
    ]
    for name, field in Settings.model_fields.items():
        env_name = field.validation_alias or name.upper()
        if not isinstance(env_name, str):
            continue
        value = '' if field.exclude else field.default
        if isinstance(value, bool):
            value = str(value).lower()
        lines.append(f'# {env_name}={value}')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    import json
    import sys
    if '--ui' in sys.argv:
        print(json.dumps(Settings.model_construct().public_ui(), indent=2))
    else:
        print(template(), end='')
