"""Create the Echora v1 schema from the original SQL migrations through 011.

Revision ID: 0001_existing_schema
"""
from alembic import op

revision = "0001_existing_schema"
down_revision = None
branch_labels = None
depends_on = None


V1_STATEMENTS = (
    'CREATE EXTENSION IF NOT EXISTS vector',
    'CREATE EXTENSION IF NOT EXISTS pgcrypto',
    'CREATE TABLE libraries (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  name text NOT NULL,\n  root_path text NOT NULL,\n  namespace uuid NOT NULL UNIQUE,\n  created_at timestamptz NOT NULL DEFAULT now()\n)',
    '-- A track is global and content-addressed. The same decoded file seen in two\n-- libraries resolves to one row and one set of model embeddings.\nCREATE TABLE users (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  username text NOT NULL UNIQUE,\n  display_name text NOT NULL,\n  password_hash text NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now()\n)',
    'CREATE TABLE user_preferences (\n  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,\n  onboarding_complete boolean NOT NULL DEFAULT false,\n  navidrome_connection_id uuid,\n  updated_at timestamptz NOT NULL DEFAULT now()\n)',
    'CREATE TABLE user_sessions (\n  token_hash text PRIMARY KEY,\n  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  expires_at timestamptz NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now()\n)',
    'CREATE INDEX user_sessions_expiry_idx ON user_sessions (expires_at)',
    'CREATE TABLE navidrome_connections (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  url text NOT NULL,\n  username text NOT NULL,\n  encrypted_password bytea NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  last_used_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (url, username)\n)',
    'ALTER TABLE user_preferences\n  ADD CONSTRAINT user_preferences_navidrome_connection_fk\n  FOREIGN KEY (navidrome_connection_id) REFERENCES navidrome_connections(id) ON DELETE SET NULL',
    "CREATE TABLE tracks (\n  id uuid PRIMARY KEY,\n  audio_hash text NOT NULL UNIQUE,\n  title text NOT NULL,\n  artist text,\n  album text,\n  year integer,\n  duration_seconds double precision NOT NULL CHECK (duration_seconds >= 0),\n  genres text[] NOT NULL DEFAULT '{}',\n  metadata jsonb NOT NULL DEFAULT '{}',\n  ingested_at timestamptz NOT NULL DEFAULT now()\n)",
    'CREATE TABLE library_tracks (\n  library_id uuid NOT NULL REFERENCES libraries(id) ON DELETE CASCADE,\n  track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  relative_path text,\n  added_at timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY (library_id, track_id)\n)',
    "CREATE TABLE track_sources (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  library_id uuid NOT NULL REFERENCES libraries(id) ON DELETE CASCADE,\n  track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  source_type text NOT NULL CHECK (source_type IN ('filesystem', 'subsonic')),\n  external_id text NOT NULL,\n  source_data jsonb NOT NULL DEFAULT '{}',\n  UNIQUE (library_id, source_type, external_id)\n)",
    "CREATE TABLE lyrics (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  source text NOT NULL CHECK (source IN ('embedded', 'local-file', 'transcribed', 'none')),\n  text text,\n  language text,\n  confidence real CHECK (confidence BETWEEN 0 AND 1),\n  provenance jsonb NOT NULL DEFAULT '{}',\n  created_at timestamptz NOT NULL DEFAULT now()\n)",
    "CREATE TABLE analysis_runs (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  kind text NOT NULL,\n  model_name text,\n  model_revision text,\n  config_hash text NOT NULL,\n  config jsonb NOT NULL,\n  environment jsonb NOT NULL DEFAULT '{}',\n  device text,\n  precision text,\n  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'complete', 'failed', 'cancelled')),\n  started_at timestamptz,\n  finished_at timestamptz,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (kind, model_name, model_revision, config_hash)\n)",
    "CREATE TABLE embeddings (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  run_id uuid NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,\n  embedding_type text NOT NULL CHECK (embedding_type IN ('audio-track', 'audio-window', 'lyrics')),\n  window_index integer,\n  window_start_seconds double precision,\n  window_end_seconds double precision,\n  dimension integer NOT NULL,\n  aggregation text,\n  embedding vector NOT NULL,\n  inference_ms integer,\n  peak_vram_bytes bigint,\n  artifact_checksum text,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE NULLS NOT DISTINCT (track_id, run_id, embedding_type, window_index)\n)",
    'CREATE INDEX embeddings_lookup_idx ON embeddings (run_id, embedding_type, track_id)',
    "CREATE TABLE evaluation_queries (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  text text NOT NULL,\n  intent text NOT NULL,\n  qualifies text NOT NULL,\n  excludes text NOT NULL,\n  split text NOT NULL DEFAULT 'evaluation' CHECK (split IN ('tuning', 'evaluation')),\n  created_at timestamptz NOT NULL DEFAULT now()\n)",
    'CREATE TABLE retrieval_results (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  query_id uuid NOT NULL REFERENCES evaluation_queries(id) ON DELETE CASCADE,\n  run_id uuid NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,\n  track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  rank integer NOT NULL CHECK (rank > 0),\n  score double precision NOT NULL,\n  latency_ms integer,\n  review_batch uuid,\n  UNIQUE (query_id, run_id, rank)\n)',
    "CREATE TABLE judgments (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  result_id uuid NOT NULL REFERENCES retrieval_results(id) ON DELETE CASCADE,\n  relevance smallint NOT NULL CHECK (relevance BETWEEN 0 AND 3),\n  notes text,\n  reviewer text NOT NULL DEFAULT 'owner',\n  judged_at timestamptz NOT NULL DEFAULT now()\n)",
    'CREATE TABLE IF NOT EXISTS users (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  username text NOT NULL UNIQUE,\n  display_name text NOT NULL,\n  password_hash text NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now()\n)',
    'CREATE TABLE IF NOT EXISTS user_preferences (\n  user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,\n  onboarding_complete boolean NOT NULL DEFAULT false,\n  navidrome_connection_id uuid REFERENCES navidrome_connections(id) ON DELETE SET NULL,\n  updated_at timestamptz NOT NULL DEFAULT now()\n)',
    'CREATE TABLE IF NOT EXISTS user_sessions (\n  token_hash text PRIMARY KEY,\n  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  expires_at timestamptz NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now()\n)',
    'CREATE INDEX IF NOT EXISTS user_sessions_expiry_idx ON user_sessions (expires_at)',
    "CREATE TABLE IF NOT EXISTS concepts (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid REFERENCES users(id) ON DELETE CASCADE,\n  name text NOT NULL,\n  description text NOT NULL DEFAULT '',\n  positive_prompts text[] NOT NULL,\n  negative_prompts text[] NOT NULL DEFAULT '{}',\n  positive_track_ids uuid[] NOT NULL DEFAULT '{}',\n  negative_track_ids uuid[] NOT NULL DEFAULT '{}',\n  enabled boolean NOT NULL DEFAULT true,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  CHECK (cardinality(positive_prompts) + cardinality(positive_track_ids) > 0)\n)",
    'CREATE UNIQUE INDEX IF NOT EXISTS concepts_user_name_idx\n  ON concepts (user_id, lower(name)) NULLS NOT DISTINCT',
    'CREATE TABLE IF NOT EXISTS concept_scores (\n  concept_id uuid NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,\n  track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  run_id uuid NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,\n  raw_score double precision NOT NULL,\n  percentile double precision NOT NULL CHECK (percentile BETWEEN 0 AND 1),\n  scored_at timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY (concept_id, track_id, run_id)\n)',
    'CREATE INDEX IF NOT EXISTS concept_scores_track_idx ON concept_scores (track_id, run_id)',
    'CREATE TABLE IF NOT EXISTS community_snapshots (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  model_name text NOT NULL,\n  semantic_weight double precision NOT NULL CHECK (semantic_weight BETWEEN 0 AND 1),\n  corpus_hash text NOT NULL,\n  algorithm_revision integer NOT NULL,\n  track_count integer NOT NULL CHECK (track_count >= 0),\n  parameters jsonb NOT NULL,\n  metrics jsonb NOT NULL,\n  payload jsonb NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (model_name, semantic_weight, corpus_hash, algorithm_revision)\n)',
    'CREATE INDEX IF NOT EXISTS community_snapshots_latest_idx\n  ON community_snapshots (model_name, semantic_weight, created_at DESC)',
    'CREATE TABLE IF NOT EXISTS track_fingerprints (\n  track_id uuid PRIMARY KEY REFERENCES tracks(id) ON DELETE CASCADE,\n  algorithm text NOT NULL,\n  algorithm_version text NOT NULL,\n  fingerprint bytea NOT NULL,\n  duration_seconds double precision NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now()\n)',
    "CREATE TABLE IF NOT EXISTS recording_groups (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  status text NOT NULL DEFAULT 'automatic' CHECK (status IN ('automatic', 'confirmed', 'rejected')),\n  canonical_track_id uuid REFERENCES tracks(id) ON DELETE SET NULL,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  updated_at timestamptz NOT NULL DEFAULT now()\n)",
    "CREATE TABLE IF NOT EXISTS recording_group_members (\n  group_id uuid NOT NULL REFERENCES recording_groups(id) ON DELETE CASCADE,\n  track_id uuid NOT NULL UNIQUE REFERENCES tracks(id) ON DELETE CASCADE,\n  confidence double precision NOT NULL CHECK (confidence BETWEEN 0 AND 1),\n  membership_status text NOT NULL DEFAULT 'automatic' CHECK (membership_status IN ('automatic', 'confirmed', 'rejected')),\n  added_at timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY (group_id, track_id)\n)",
    "CREATE TABLE IF NOT EXISTS recording_match_evidence (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  left_track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  right_track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  decision text NOT NULL CHECK (decision IN ('matched', 'rejected', 'review')),\n  chromaprint_score double precision,\n  duration_delta_seconds double precision,\n  semantic_similarity double precision,\n  acoustic_similarity double precision,\n  matcher_revision integer NOT NULL,\n  evidence jsonb NOT NULL DEFAULT '{}',\n  created_at timestamptz NOT NULL DEFAULT now(),\n  CHECK (left_track_id < right_track_id),\n  UNIQUE (left_track_id, right_track_id, matcher_revision)\n)",
    'CREATE INDEX IF NOT EXISTS track_fingerprints_duration_idx ON track_fingerprints (duration_seconds)',
    'CREATE INDEX IF NOT EXISTS recording_match_tracks_idx ON recording_match_evidence (left_track_id, right_track_id)',
    'CREATE TABLE IF NOT EXISTS artist_profiles (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  artist_key text NOT NULL,\n  artist_name text NOT NULL,\n  model_name text NOT NULL,\n  corpus_hash text NOT NULL,\n  track_count integer NOT NULL CHECK (track_count > 0),\n  component_count integer NOT NULL CHECK (component_count > 0),\n  payload jsonb NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (artist_key, model_name, corpus_hash)\n)',
    'CREATE INDEX IF NOT EXISTS artist_profiles_name_idx ON artist_profiles (lower(artist_name))',
    "ALTER TABLE lyrics ADD COLUMN IF NOT EXISTS availability_status text NOT NULL DEFAULT 'available'",
    'ALTER TABLE lyrics DROP CONSTRAINT IF EXISTS lyrics_availability_status_check',
    "ALTER TABLE lyrics ADD CONSTRAINT lyrics_availability_status_check\n  CHECK (availability_status IN ('available', 'missing', 'unavailable', 'instrumental'))",
    'CREATE UNIQUE INDEX IF NOT EXISTS lyrics_track_idx ON lyrics (track_id)',
    'CREATE INDEX IF NOT EXISTS lyrics_language_idx ON lyrics (language) WHERE text IS NOT NULL',
    'CREATE TABLE IF NOT EXISTS user_libraries (\n  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  library_id uuid NOT NULL REFERENCES libraries(id) ON DELETE CASCADE,\n  added_at timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY (user_id, library_id)\n)',
    'CREATE INDEX IF NOT EXISTS user_libraries_library_idx\n  ON user_libraries (library_id, user_id)',
    "-- Preserve visibility for users whose selected Navidrome connection already\n-- resolves to a shared library.\nINSERT INTO user_libraries (user_id, library_id)\nSELECT preferences.user_id, libraries.id\nFROM user_preferences AS preferences\nJOIN navidrome_connections AS connections\n  ON connections.id = preferences.navidrome_connection_id\nJOIN libraries\n  ON lower(rtrim(libraries.root_path, '/')) = lower(rtrim(connections.url, '/'))\nON CONFLICT DO NOTHING",
    "CREATE TABLE IF NOT EXISTS curations (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  navidrome_connection_id uuid NOT NULL REFERENCES navidrome_connections(id) ON DELETE CASCADE,\n  name text NOT NULL,\n  positive_prompt text NOT NULL,\n  negative_prompt text NOT NULL DEFAULT '',\n  track_limit integer NOT NULL DEFAULT 30 CHECK (track_limit BETWEEN 5 AND 200),\n  refresh_mode text NOT NULL DEFAULT 'stable' CHECK (refresh_mode IN ('stable', 'fresh')),\n  refresh_enabled boolean NOT NULL DEFAULT true,\n  refresh_interval_hours integer NOT NULL DEFAULT 6 CHECK (refresh_interval_hours = 6),\n  navidrome_playlist_id text,\n  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'refreshing', 'ready', 'failed')),\n  last_error text,\n  last_refreshed_at timestamptz,\n  next_refresh_at timestamptz,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  updated_at timestamptz NOT NULL DEFAULT now()\n)",
    'CREATE UNIQUE INDEX IF NOT EXISTS curations_user_name_idx\n  ON curations (user_id, lower(name))',
    'CREATE INDEX IF NOT EXISTS curations_due_idx\n  ON curations (next_refresh_at)\n  WHERE refresh_enabled',
    'CREATE TABLE IF NOT EXISTS curation_revisions (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  curation_id uuid NOT NULL REFERENCES curations(id) ON DELETE CASCADE,\n  revision_number integer NOT NULL,\n  recipe jsonb NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (curation_id, revision_number)\n)',
    "CREATE TABLE IF NOT EXISTS curation_revision_tracks (\n  revision_id uuid NOT NULL REFERENCES curation_revisions(id) ON DELETE CASCADE,\n  position integer NOT NULL CHECK (position >= 0),\n  track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  score real NOT NULL,\n  evidence jsonb NOT NULL DEFAULT '{}',\n  source_id text NOT NULL,\n  PRIMARY KEY (revision_id, position),\n  UNIQUE (revision_id, track_id)\n)",
    'CREATE INDEX IF NOT EXISTS curation_revision_tracks_track_idx\n  ON curation_revision_tracks (track_id)',
    'CREATE TABLE IF NOT EXISTS user_track_links (\n  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n  library_id uuid NOT NULL REFERENCES libraries(id) ON DELETE CASCADE,\n  track_id uuid NOT NULL REFERENCES tracks(id) ON DELETE CASCADE,\n  external_id text NOT NULL,\n  linked_at timestamptz NOT NULL DEFAULT now(),\n  last_seen_at timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY (user_id, library_id, track_id),\n  UNIQUE (user_id, library_id, external_id)\n)',
    'CREATE INDEX IF NOT EXISTS user_track_links_track_idx\n  ON user_track_links (user_id, track_id)',
    "-- Preserve current visibility. The next synchronization reconciles this set\n-- against the user's live Navidrome catalog.\nINSERT INTO user_track_links (user_id, library_id, track_id, external_id)\nSELECT ul.user_id, ul.library_id, ts.track_id, ts.external_id\nFROM user_libraries ul\nJOIN track_sources ts ON ts.library_id=ul.library_id\nWHERE ts.source_type='subsonic'\nON CONFLICT DO NOTHING",
    "CREATE INDEX IF NOT EXISTS tracks_title_sort_idx\n  ON tracks (lower(title), lower(coalesce(artist, '')), id)",
    'CREATE INDEX IF NOT EXISTS tracks_artist_sort_idx\n  ON tracks (lower(artist), lower(title), id)\n  WHERE artist IS NOT NULL',
    'CREATE INDEX IF NOT EXISTS tracks_release_sort_idx\n  ON tracks (year DESC NULLS LAST, lower(title), id)',
    'CREATE INDEX IF NOT EXISTS track_sources_track_lookup_idx\n  ON track_sources (track_id, source_type, library_id, external_id)',
)


def upgrade() -> None:
    connection = op.get_bind()
    for statement in V1_STATEMENTS:
        connection.exec_driver_sql(statement)


def downgrade() -> None:
    # The v1 baseline may contain application data. Downgrading it is intentionally unsupported.
    pass
