"""Explicitly consented calibration recordings. No automatic recognition decisions.

Raw clips live only in a private, non-web-served directory. PostgreSQL holds owner,
ground-truth label, consent and expiry. UUID filenames are generated by the server.
Disk publication/deletion and expiry share a database advisory lock across replicas.
"""
from __future__ import annotations

from .settings import get_settings

import hashlib
import os
from pathlib import Path
import time
from uuid import UUID, uuid4

from . import jobs
from .recording_search import SAMPLE_RATE, QueueFull, decode_query

CONSENT_VERSION = "save-for-calibration-v1"
_LOCK = "recording-calibration-storage-v1"
_PUBLIC = ("id", "expected_track_id", "not_in_library", "notes", "duration_seconds",
           "created_at", "expires_at", "expected_title", "expected_artist")


class CalibrationDisabled(ValueError):
    pass


class TrackUnavailable(ValueError):
    pass


def enabled() -> bool:
    return get_settings().recording_calibration_enabled


def directory() -> Path:
    return Path(get_settings().recording_calibration_dir)


def _file(root: Path, sample_id) -> Path:
    return root / f"{UUID(str(sample_id))}.audio"


def _public(row):
    return {key: str(value) if isinstance(value, UUID) else value
            for key in _PUBLIC if (value := row.get(key)) is not None}


def _lock(db):
    db.execute("SELECT pg_advisory_xact_lock(hashtextextended(%s,0))", (_LOCK,))


def save(user_id, audio: bytes, *, expected_track_id=None, not_in_library=False,
         notes="", consent=None):
    if not enabled():
        raise CalibrationDisabled("Calibration collection is disabled")
    if consent != CONSENT_VERSION:
        raise ValueError("Explicit consent to save this calibration clip is required")
    if (expected_track_id is not None) == bool(not_in_library):
        raise ValueError("Choose the actual library song or mark the clip as not in your library")
    if not isinstance(notes, str) or len(notes) > 300:
        raise ValueError("Calibration notes must be at most 300 characters")
    if not audio or len(audio) > get_settings().recording_max_upload_bytes:
        raise ValueError("Invalid calibration recording size")
    owner = UUID(str(user_id))
    expected = UUID(str(expected_track_id)) if expected_track_id is not None else None
    if expected is not None:
        with jobs._db() as db:
            if not db.execute("SELECT 1 FROM user_track_links WHERE user_id=%s AND track_id=%s",
                              (owner, expected)).fetchone():
                raise TrackUnavailable("This song is not available in your library")
    # Validation is bounded decoding only, not model inference. Do not put private
    # query audio into the shared library preprocessing cache.
    samples = decode_query(audio)
    duration = len(samples) / SAMPLE_RATE
    del samples
    if duration < 1:
        raise ValueError("Record at least one second of audio")
    root = directory()
    root.mkdir(parents=True, exist_ok=True, mode=0o700)
    root.chmod(0o700)
    sample_id = uuid4()
    path = _file(root, sample_id)
    written = False
    try:
        with jobs._db() as db:
            _lock(db)
            quota = db.execute("""SELECT count(*) AS total,
                count(*) FILTER (WHERE user_id=%s) AS owned,
                count(*) FILTER (WHERE user_id=%s AND created_at>now()-interval '1 minute') AS recent
                FROM recording_calibration_samples""", (owner, owner)).fetchone()
            # Expired rows count until cleanup erases their files, bounding disk
            # retention even while a worker is stopped.
            if quota["total"] >= get_settings().recording_calibration_max_total_samples or quota["owned"] >= get_settings().recording_calibration_max_user_samples or quota["recent"] >= get_settings().recording_calibration_uploads_per_minute:
                raise QueueFull("Calibration storage is full. Delete a saved clip or try later.")
            if expected is not None and not db.execute(
                    "SELECT 1 FROM user_track_links WHERE user_id=%s AND track_id=%s",
                    (owner, expected)).fetchone():
                raise TrackUnavailable("This song is not available in your library")
            row = db.execute("""INSERT INTO recording_calibration_samples
                (id,user_id,expected_track_id,not_in_library,notes,consent_version,
                 audio_sha256,byte_count,duration_seconds,expires_at)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,now()+%s*interval '1 second') RETURNING *""",
                             (sample_id, owner, expected, bool(not_in_library), notes.strip(), CONSENT_VERSION,
                              hashlib.sha256(audio).hexdigest(), len(audio), duration, get_settings().recording_calibration_retention_seconds)).fetchone()
            fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
            written = True
            with os.fdopen(fd, "wb") as stream:
                stream.write(audio)
                stream.flush()
                os.fsync(stream.fileno())
            # Make the directory entry durable before publishing the DB row.
            directory_fd = os.open(root, os.O_RDONLY | os.O_DIRECTORY)
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
        return _public(row)
    except BaseException:
        if written:
            path.unlink(missing_ok=True)
        raise


def list_samples(user_id):
    with jobs._db() as db:
        rows = db.execute("""SELECT s.*,t.title AS expected_title,t.artist AS expected_artist
            FROM recording_calibration_samples s
            LEFT JOIN tracks t ON t.id=s.expected_track_id AND EXISTS (
                SELECT 1 FROM user_track_links u WHERE u.user_id=s.user_id AND u.track_id=t.id)
            WHERE s.user_id=%s AND s.expires_at>now() ORDER BY s.created_at DESC,s.id
            LIMIT %s""", (UUID(str(user_id)), get_settings().recording_calibration_max_user_samples)).fetchall()
    return {"samples": [_public(row) for row in rows]}


def delete(sample_id, user_id) -> bool:
    with jobs._db() as db:
        _lock(db)
        row = db.execute("SELECT id FROM recording_calibration_samples WHERE id=%s AND user_id=%s FOR UPDATE",
                         (UUID(str(sample_id)), UUID(str(user_id)))).fetchone()
        if row is None:
            return False
        # Unlink first: failed deletion never reports success while keeping audio.
        _file(directory(), row["id"]).unlink(missing_ok=True)
        db.execute("DELETE FROM recording_calibration_samples WHERE id=%s", (row["id"],))
    return True


def cleanup():
    """Expire consented files; recover orphaned files after failed/crashed saves.

    Runs even when collection is disabled. Young orphans get a five-minute grace
    period. Only canonical UUID .audio filenames under this feature's root qualify.
    """
    root = directory()
    with jobs._db() as db:
        if not db.execute("SELECT pg_try_advisory_xact_lock(hashtextextended(%s,0)) AS locked",
                          (_LOCK,)).fetchone()["locked"]:
            return
        expired = db.execute("SELECT id FROM recording_calibration_samples WHERE expires_at<=now() FOR UPDATE").fetchall()
        for row in expired:
            _file(root, row["id"]).unlink(missing_ok=True)
            db.execute("DELETE FROM recording_calibration_samples WHERE id=%s", (row["id"],))
        retained = {str(row["id"]) for row in db.execute("SELECT id FROM recording_calibration_samples")}
        now = time.time()
        if root.exists():
            for path in root.glob("*.audio"):
                try:
                    sample_id = str(UUID(path.stem))
                except ValueError:
                    continue
                if path.name != f"{sample_id}.audio":
                    continue
                try:
                    if sample_id not in retained and now - path.lstat().st_mtime > 300:
                        path.unlink(missing_ok=True)
                except FileNotFoundError:
                    pass
